### PR TITLE
Disable stdout/stderr buffering for Sublime Text/Python

### PR DESCRIPTION
**Pull request by lukexi**
Yo!

A heads up — I put together a Sublime Text 3 plugin over the weekend based on ide-backed/client and it is just crazy fast and wonderful (even with just autocomplete, error regions and type-at-cursor it already blows away SublimeHaskell for me!). Thanks a ton for all the work.

https://github.com/lukexi/Rawhide

I had to disable buffering on stdout/stderr along with the other pull request to get Python's subprocess.Popen to receive things reliably from the ide-backend-client executable; I can put together a minimal repro if you want try finding another way (I tried just calling hFlush after hPutStrLn and screwing around with every option I could find in Popen, this was the only thing that worked).

### CODE REVIEW

**Comment by lukexi** [comment]
Oh, just discovered development has moved to https://github.com/commercialhaskell/stack-ide. I'm porting over now.

If you're into centralizing plugins for the major editors into the stack-ide repo itself, I'm definitely down to do that (I think it would keep the community more focused!) — the Sublime Text plugin is just a single python file.

**Comment by chrisdone** [comment]
Yep, the plan is to just assume Stack so we can focus on a smooth user experience. I can add you as a maintainer to that repo if you're onboard with that.

**Comment by lukexi** [comment]
Great — super onboard.

**Comment by chrisdone** [comment]
I've moved this repo to stack-ide so that people going to chrisdone/ide-backend-client will arrive here.

**Comment by lukexi** [comment]
Closing in favor of #13

**Pull request closed without merging**
