### PR TITLE
Added README and Commentary documentation.

### PR DESCRIPTION
**Pull request by lukehoersten**
Added docs and commentary to comply with #68 requests from melpa maintainer.

### CODE REVIEW

**Comment by lukehoersten** [comment]
@chrisdone I should have pulled this out as a separate commit form the rename in the first place. Sorry about that. This should be enough to get a melpa package out there which I think is an important step for getting more testers. I've been running `stack-mode` now as my main `ghc-mod` replacement and it's been excellent!

**Comment by chrisdone** [comment]
Cool!

**Comment by lukehoersten** [comment]
You OK with merging these docs in or no?

**Comment by chrisdone** [comment]
I thought I clicked merge.

**Comment by lukehoersten** [comment]
Thanks Chris.

**Pull request merged**
