### PR TITLE
switch default stack.yml to lts-3.0

### PR DESCRIPTION
**Pull request by rvion**

### CODE REVIEW

**Comment by rvion** [comment]
Also, not sure if this is a good idea to switch to lts-3.0 since it's already working fine as of now

**Comment by rvion** [comment]
closing since it doesn't add much

**Comment by mgsloan** [comment]
Thanks for the PR anyway!  I've been focused on other things and hadn't seen it till recently.

**Comment by rvion** [comment]
No prob :)

**Pull request closed without merging**
